[project]
name = "simple-rtmw"
version = "0.1.0"
description = "RTMW simple rtmw inference"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "onnxruntime>=1.22.1",
    "opencv-python>=4.11.0.86",
    "tqdm>=4.67.1",
]
